# Generated by Django 4.1.4 on 2023-08-09 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="currency name"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="currency code"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduledPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="payment name")),
                ("due_date", models.DateField(verbose_name="due date")),
                (
                    "periodicity",
                    models.DurationField(
                        blank=True, null=True, verbose_name="periodicity"
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("amount", models.FloatField(verbose_name="amount")),
                ("created", models.DateField(auto_now_add=True)),
                ("modified", models.DateField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="category"
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="planner.currency",
                    ),
                ),
            ],
        ),
    ]
